### ISSUE TITLE
[feature] centralize tags

### ISSUE THREAD

**Issue by masukomi** [masukomi/backup_brain#70]
currently tags are stored as an array of strings embedded in a `Bookmark` document.

## Current thinking
Hybrid approach, with denormalized data. 
- `Bookmark` has an embedded array of strings called `tags` 
- `Tag` is a new object that gets updated after create. this acts as our centralized list for things like autocomplete, and displaying ALL tags. 

### TODO
- [x] combine tags to filter results
- [x] filter search results with tags
- [x] show list of tags present in current search / tag results list
- [x] global renaming of a tag 
- [x] merging of tags
  - this is done by renaming a tag to match another tag & prolly needs good docs. 

## Problems remaining 
- [ ] removing a tag from the last boomark with that tag does NOT remove it from the centralized list.     

## OLD THINKING
I'm thinking it should switch to use [mongoid_tagglable](https://github.com/ches/mongoid_taggable/) (fork)

Note that [the fork's upstream repo](https://github.com/wilkerlucio/mongoid_taggable) has [some more recent commits](https://github.com/ches/mongoid_taggable/compare/integration...wilkerlucio%3Amongoid_taggable%3Amaster) that may be worth considering, but i don't _think_ so. I think the fork's gone off in a different direction which makes most, if not all, of these irrelevant.

If the gem doesn't look good after testing, this would need to change to be a [has_and_belongs_to_many](https://www.mongodb.com/docs/mongoid/current/reference/associations/#has-and-belongs-to-many) relationship (Mongoid driver never adopted `has_many_through`)

**Comment by masukomi** [comment]
done! merged into `next` Will probably release next week.
